### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by trebmuh** [brummer10/XTuner#3]
I would very like to be able to use the "Do Ré Mi Fa Sol La Si" notation, rather than "C D E F G A B".
Would that be possible?

**Comment by brummer10** [comment]
Hi @trebmuh 

For the notation we need to go a other route then the usual gettext(). 
For performance reason XTuner use a const char array for the notation, this is not translatable by design. 
So, I've added the French notations as well as hardcoded const char arrays and check during initialisation for the locale settings. If we found "FR" in the settings, the French notation will be used. As there are no more strings to be translated I haven't implemented gettext() here, but it should show now the notation you prefer anyway.

regards
hermann

**Comment by trebmuh** [comment]
Rebuild from master f8e92f1 and it works for me.
Thanks you very much.
